### ISSUE TITLE
tau propagation is unphysical

### ISSUE THREAD

**Issue by ibsafa** [tudo-astroparticlephysics/PROPOSAL#183] opened 2021-06-30 19:49 UTC
when propagating taus through ice, outgoing taus show final energies of ~2-3 GeV. this is unphysical, as taus never decay "at rest" due to their extremely short lifetime. in the code below, the energy I'm talking about is 'en_at_decay'

python code:
import proposal as pp
 
        sec_def = pp.SectorDefinition()
        sec_def.medium = pp.medium.Ice(1.0)
        sec_def.geometry = pp.geometry.Sphere(pp.Vector3D(), 1e20, 0)
        sec_def.particle_location = pp.ParticleLocation.inside_detector

        sec_def.scattering_model = pp.scattering.ScatteringModel.Moliere
        sec_def.crosssection_defs.brems_def.lpm_effect = True
        sec_def.crosssection_defs.epair_def.lpm_effect = True

        sec_def.cut_settings.ecut = 500
        sec_def.cut_settings.vcut = 0.1

        sec_def.crosssection_defs.photo_def.parametrization = pp.parametrization.photonuclear.PhotoParametrization.BlockDurandHa

        interpolation_def = pp.InterpolationDef()
        interpolation_def.path_to_tables = "~/.local/share/PROPOSAL/tables"
        interpolation_def.path_to_tables_readonly = "~/.local/share/PROPOSAL/tables"

        #define propagator
        prop = pp.Propagator(
                particle_def=pp.particle.TauMinusDef(),
                sector_defs=[sec_def],
                detector=pp.geometry.Sphere(pp.Vector3D(), 1e20, 0),
                interpolation_def=interpolation_def
        )

            sec = propagator.propagate(tau)
            particles = sec.particles
            tau_length.append(sec.position[-1].magnitude() / 100)
            decay_products = [p for i,p in zip(range(max(len(particles)-3,0),len(particles)), particles[-3:]) if int(p.type) <= 1000000001]
            en_at_decay.append(np.sum([p.energy for p in decay_products]))

**Comment by Jean1995** [comment] 2021-06-30 20:01
What version of PROPOSAL are you using to run the script?

**Comment by ibsafa** [comment] 2021-06-30 20:02
v6.1.6

**Comment by Jean1995** [comment] 2021-07-06 15:28
I am able to reproduce this issue for high initial tau energies. In some cases, the final energy of the tau after propagation is very low. This seems to be caused by very stochastic pair production losses, which cause the tau to lose almost all its energy.

It looks like this is caused by an interpolation issue in the pair production parametrization. In principle, it looks like this problem can be solved by telling PROPOSAL not to use the interpolated version of the pair production parametrization. However, I don't think there is a way to enforce this behavior without changing the PROPOSAL source code.

As a workaround, you may try to increase the number of interpolation nodes using `interpolation_def.nodes_cross_section = 200`. By default, this is set to 100 nodes. In my case (propagating taus with an initial energy of 1e14 MeV), I set `nodes_cross_section` to 200. With this setting, I was able to propagate 100 taus with no unphysically high losses.

You might have to tweak the exact number of `nodes_cross_section` for your application case, since setting it too high may have a negative impact on the performance while setting it too low might not solve the problem with the unphysically high losses.

**Comment by ibsafa** [comment] 2021-07-12 17:32
Can you please send me an example of how you ran it and got reasonable output? 
I raised the cross section nodes to 200 and I still get weird output, maybe I'm messing something else up when I set up the interpolator / propagator. thanks

**Comment by Jean1995** [comment] 2021-07-13 08:45
> Can you please send me an example of how you ran it and got reasonable output?

This is the script I used for testing:

```
import proposal as pp
import numpy as np

sec_def = pp.SectorDefinition()
sec_def.medium = pp.medium.Ice(1.0)
sec_def.geometry = pp.geometry.Sphere(pp.Vector3D(), 1e20, 0)
sec_def.particle_location = pp.ParticleLocation.inside_detector
sec_def.scattering_model = pp.scattering.ScatteringModel.Moliere
sec_def.crosssection_defs.brems_def.lpm_effect = True
sec_def.crosssection_defs.epair_def.lpm_effect = True

sec_def.cut_settings.ecut = 500
sec_def.cut_settings.vcut = 0.1

sec_def.crosssection_defs.photo_def.parametrization = pp.parametrization.photonuclear.PhotoParametrization.BlockDurandHa

interpolation_def = pp.InterpolationDef()
interpolation_def.path_to_tables = "~/.local/share/PROPOSAL/tables"
interpolation_def.path_to_tables_readonly = "~/.local/share/PROPOSAL/tables"
interpolation_def.nodes_cross_section = 200

#define propagator
prop = pp.Propagator(
    particle_def=pp.particle.TauMinusDef(),
    sector_defs=[sec_def],
    detector=pp.geometry.Sphere(pp.Vector3D(), 1e20, 0),
    interpolation_def=interpolation_def
)

tau = pp.particle.DynamicData(pp.particle.TauMinusDef().particle_type)
tau.energy = 1e14

tau_length = []   
en_at_decay = []
for i in range(50):
    sec = prop.propagate(tau)
    particles = sec.particles
    tau_length.append(sec.position[-1].magnitude() / 100)
    decay_products = [p for i,p in zip(range(max(len(particles)-3,0),len(particles)), particles[-3:]) if int(p.type) <= 1000000001]
    en_at_decay.append(np.sum([p.energy for p in decay_products]))

print(min(en_at_decay))
```

With the line `interpolation_def.nodes_cross_section = 200`, the output is `91901006089.87488`. Without this line (or when I replace the 200 with a 100), the output is `1862.5371407807338`.

Maybe you are using different initial conditions?

**Comment by ibsafa** [comment] 2021-07-13 22:00
So I'm using the exact same definitions here. the only exception is that I define a tau.position and tau.direction before propagating. If I comment those lines out to match your code, I get all nans for the decay energy which is very strange.

**Comment by ibsafa** [comment] 2021-07-14 20:48
ok I figured it out. there was a stupid bug in my code that was passing the wrong energies. after fixing that, and increasing the number of nodes, I now get reasonable results. thanks!

**Comment by maxnoe** [comment] 2021-07-16 16:43
Is there any reasonable heuristic to determine the needed number of nodes so that users don't have to care to set a good value?

This is a sort of very hard to trace bugs if it silently produces non-sensical results. Reopening, as that is a behavior that should never happen (silently producing unphysical results)

**Comment by Jean1995** [comment] 2021-07-19 16:27
> Is there any reasonable heuristic to determine the needed number of nodes so that users don't have to care to set a good value?
> 
> This is a sort of very hard to trace bugs if it silently produces non-sensical results. Reopening, as that is a behavior that should never happen (silently producing unphysical results)

This issue is specific for version 6.1.6 of PROPOSAL since here, the outer nodes of the interpolation tables have been set not directly to the maximum/minimum values of the phase space but only very close. It is already known that this can cause issues (see for example #123). However, this has been fixed in PROPOSAL 7 (and I also double-checked that this exact bug does not occur anymore in PROPOSAL 7). I am not sure how to handle bugs and issues of old code versions, do we keep them open in git?

> This is a sort of very hard to trace bugs if it silently produces non-sensical results. Reopening, as that is a behavior that should never happen (silently producing unphysical results)

However, this is still a very good question. At the moment, the UnitTests only cover some basic parameter combinations (i.e. combinations of particles, media, cut settings, etc.). To solve this issue, I already had the idea some time ago to introduce "consistency checks" for the interpolation routines. They would conduct a detailed test of the interpolation routine (by comparing them to the integrated values) based on the input of a user. This way, users could check whether they need to adjust some interpolation settings to get physical results. But this idea rather belongs into issue #171.

**Closed** 2021-07-20 06:44 UTC
Labels: PROPOSAL 6, bug
