### ISSUE TITLE
verbose math method and python interface to logging level

### ISSUE THREAD

**Issue by clark2668** [tudo-astroparticlephysics/PROPOSAL#106] opened 2020-09-08 18:30 UTC
When propagating particles, the following error prints often (many thousands of times) to the terminal:

`WARN - Maximum number of iteration exeeded in NewtonRaphson`

Which clutters the command line and makes log files very large.

It looks like it comes from a warn level message in the math methods:

https://github.com/tudo-astroparticlephysics/PROPOSAL/blob/master/private/PROPOSAL/math/MathMethods.cxx#L270

It would be nice if the python interface provided a way to adjust the logging level, so that people who install proposal through pypi can control the logging level. If that is present and I missed it, sorry!

Also, perhaps this indicates the logging level on that particular problem should be turned down to `INFO`?

**Comment by Jean1995** [comment] 2020-09-22 10:17
Sorry for the delayed answer!

At the moment, it is not possible to set the logging level in the python interface. We will fix this for the next (major) release.

However, PROPOSAL should not run into this warning under normal circumstances. Could you provide information on your propagation process that caused this warning (particle type, energies, cuts, medium, etc.), or a minimal working example so we could backtrace this error? Thank you in advance!

**Comment by wjwoodley** [comment] 2020-11-25 06:32
Hello,

I have also experienced this warning being printed to the terminal many times, with the following code and configuration file. I notice it only appears for very high energies. Is there a maximum energy PROPOSAL should be used with?

```
import proposal as pp

# Configure the propagator

prop   = pp.Propagator(particle_def = pp.particle.MuMinusDef(), config_file = "MWE_Configuration.json")
mu_def = prop.particle_def
mu     = pp.particle.DynamicData(mu_def.particle_type)

pp.RandomGenerator.get().set_seed(500)

# Set the muon information

mu.position            = pp.Vector3D(0, 0, 6e8)
mu.direction           = pp.Vector3D(0, 0, -1)
mu.energy              = 5e13 # 5e13 MeV = 50 EeV
mu.propagated_distance = 0

# Propagate the muon

secondaries = prop.propagate(mu, 1e5)

# Print the energy of the last secondary

print(secondaries.energy[-1])
```

Contents of ```MWE_Configuration.json```:

```
{
    "global":
    {
        "seed" : 0,
        "continous_loss_output" : false,
        "only_loss_inside_detector" : true,

        "interpolation":
        {
            "path_to_tables" : ["Tables"],
            "path_to_tables_readonly" : ["Tables"],
            "do_interpolation" : true,
            "do_binary_tables" : false,
            "just_use_readonly_path" : false
        },

        "exact_time" : false,
        "scattering" : "NoScattering",
        "stopping_decay" : true,

        "brems_multiplier" : 1,
        "photo_multiplier" : 1,
        "ioniz_multiplier" : 1,
        "epair_multiplier" : 1,
        "ioniz": "IonizBetheBlochRossi",
        "epair": "EpairKelnerKokoulinPetrukhin",
        "brems" : "BremsKelnerKokoulinPetrukhin",
        "photo" : "PhotoAbramowiczLevinLevyMaor97",
        "annihilation": "none",
        "compton" : "none",
        "photopair": "none",
        "mupair": "none",
        "weak": "none",
        "lpm" : false,
        "photo_hard_component" : false,
        "photo_shadow" : "ShadowButkevichMikhailov",

        "cuts_infront":
        {
            "e_cut": -1.0,
            "v_cut": 0.001,
            "cont_rand": false
        },
        "cuts_inside":
        {
            "e_cut": 5000000.0,
            "v_cut": -1.0,
            "cont_rand": false
        },
        "cuts_behind":
        {
            "e_cut": -1.0,
            "v_cut": -1.0,
            "cont_rand": false
        },
        "medium": "air",
        "geometry":
        {
            "shape": "box",
            "origin": [0, 0, 0],
            "height": 1000000000,
            "length": 1000000000,
            "width": 1000000000
        }

    },

    "sectors": [
        {
            "hierarchy": 1,
            "medium": "standardrock",
            "density_correction": 1.0,

            "geometry":
            {
                "shape": "box",
                "origin": [0, 0, 0],
                "height": 18000000,
                "length": 18000000,
                "width": 18000000
            }
        }
    ],

    "detector":
    {
        "shape": "box",
        "origin" : [0, 0, 0],
        "height": 18000000,
        "length": 18000000,
        "width": 18000000
    }
}
```

**Comment by Jean1995** [comment] 2020-11-26 13:56
Thank you for the report and the minimal example. 
In principle, PROPOSAL does not have a maximum energy limit. However, for energies above 10e14 MeV, the `InterpolationDef` options need to be adjusted since per default, interpolation tables are only built up to 10e14 MeV.

I was able to reproduce the issue and confirm that it is a bug, although it does not significantly affect the physical correctness of the results:

The error occurs when PROPOSAL tries to calculate the final particle energy for a given propagation distance. If the final energy is too high, the Newton-Raphson method goes into an endless loop since it is unable to reach the preset absolute accuracy (of 0.01 MeV). This happens because the difference between 1e-3 MeV and, e.g. 1e19 MeV, is above the double precision of C++.

Since we will use a different method for this calculation in the next major release of PROPOSAL, this issue should not appear there. **However, I will work on a fix that we will publish in a minor release so this issue will also be fixed in the current version of PROPOSAL**.

**Comment by maxnoe** [comment] 2020-11-27 13:04
the "logging interface" part of the issue was not solved

**Comment by clark2668** [comment] 2020-11-27 17:55
Thanks for all your great work on this, and sorry I wasn't able to furnish the example myself!

**Closed** 2021-04-07 08:37 UTC
Labels: feature
